### ISSUE TITLE
Pin map for Atom lite not here

### ISSUE THREAD

**Issue by mrohner** [m5stack/M5Atom#11]

**Comment by erniberni** [comment]
I was also searching for this.

**Comment by jourdant** [comment]
Hi there - pin maps for both the Atom Lite and Atom Matrix are missing from this repo as shown here: 

<img width="336" alt="Screen Shot 2020-05-09 at 8 43 57 PM" src="https://user-images.githubusercontent.com/230794/81468784-d6a0b600-9235-11ea-901b-bc68575722e1.png">

This screenshot was taken from the README.md shown here: https://github.com/m5stack/M5Atom

**Comment by Hades2001** [comment]
Thanks, We removed invalid URL.
