### ISSUE TITLE
LEDDisplay fails to compile

### ISSUE THREAD

**Issue by dpharris** [m5stack/M5Atom#22]
pins_arduino.h contained: 
`static const uint8_t G22 = 21;`
`static const uint8_t G22 = 22;`

I changed this to:
`static const uint8_t G21 = 21;`
`static const uint8_t G22 = 22;`

And now it compiles.

**Comment by johnwargo** [comment]
I don't see a file called `pins_arduino.h` anywhere in this repo.

**Comment by Tinyu-Zhao** [comment]
We have now fixed this [issue](https://github.com/espressif/arduino-esp32/blob/4a341c94aacc27319b8764eba23dc311e7943fb6/variants/m5stack_atom/pins_arduino.h#L23)
