### ISSUE TITLE
LED_Display.h => LED_DisPlay.h

### ISSUE THREAD

**Issue by doctortee** [m5stack/M5Atom#24]
Hi !

Latest commit (32cc216) introduced a problem with file names.

In fact, you're including in M5Atom.h and LED_DisPlay.cpp a file named "LED_DisPlay.h", which doesn't exist. I think you forgot to rename LED_Display.h...
Temporary workaround was to manually rename the file...
(Sorry, I'm not used to Github, so I don't really know how to make a pull request for this)

Thanks !

**Comment by Hades2001** [comment]
Thanks for your suggestion, we have fixed this problem and uploaded new code.
