### ISSUE TITLE
LEDDisplay Still Fails to compile

### ISSUE THREAD

**Issue by jhugery** [m5stack/M5Atom#25]
Loading the LEDDisplay.ino this fails to compile with the following error.

D:\Documents\Arduino\libraries\M5Atom\examples\Basics\LEDDisplay\LEDDisplay.ino: In function 'void setup()':

LEDDisplay:23:53: error: 'LED_Display' has not been declared

     M5.dis.animation((uint8_t *)AtomImageData, 200, LED_Display::kMoveLeft, 18);

                                                     ^

exit status 1
'LED_Display' has not been declared

To resolve had to adjust the line:
  M5.dis.animation((uint8_t *)AtomImageData, 200, LED_Display::kMoveLeft, 18);
to read
  M5.dis.animation((uint8_t *)AtomImageData, 200, LED_DisPlay::kMoveLeft, 18);

This resolved the issue

**Comment by Hades2001** [comment]
Thanks for your suggestion, we have fixed this problem and uploaded new code.
