### ISSUE TITLE
LEDDisplay doesn't display anything 

### ISSUE THREAD

**Issue by johnwargo** [m5stack/M5Atom#28]
The sample [LEDDisplay](https://github.com/m5stack/M5Atom/tree/master/examples/Basics/LEDDisplay) app has a typo:

```c
//    M5.dis.animation((uint8_t *)AtomImageData, 200, LED_DisPlay::kMoveLeft, 18);
    M5.dis.animation((uint8_t *)AtomImageData, 200, LED_Display::kMoveLeft, 18);
```

but even with that fix, the sketch runs on the device, but nothing appears on the display. 

I see that there's PRs attempting to fix related issues, any chance someone from M5Stack can look at all those PRs and fix the sample apps?

**Comment by KodeMunkie** [comment]
+1 for this, should be an easy fix - looks like somebody renamed a method based on an M5Atom.h change but didn't test the code.

**Comment by johnwargo** [comment]
@Tinyu-Zhao I see you closed it - why? Was this resolved? Have you merged the related pull requests? 

Standard GitHub protocol for closing issues says that you should explain why you're closing it and, if appropriate, link the issue to the action that fixed the issue.

**Comment by Tinyu-Zhao** [comment]
> @Tinyu-Zhao I see you closed it - why? Was this resolved? Have you merged the related pull requests?
> 
> Standard GitHub protocol for closing issues says that you should explain why you're closing it and, if appropriate, link the issue to the action that fixed the issue.

https://github.com/m5stack/M5Atom/pull/20
https://github.com/m5stack/M5Atom/tree/master/examples/Basics/LEDDisplay
You can try it,If you have any other questions, please contact me.
