### ISSUE TITLE
[Library Manager] M5Atom Arduino Library did not build with IMU.getAttitude()

### ISSUE THREAD

**Issue by kentwidens** [m5stack/M5Atom#34]
I had to manually patch the M5Atom Library that I downloaded this week from Arduino's Library Manager to add MPU6886.getAttitude().

It's correctly included here but MPU6886.h in the ALM doesn't have it. The header file needs a public method declaration and the cpp file needs the method definition. The header file also needs three private variables for getAttitude to do its thing:
    private:
        float _last_theta = 0;
        float _last_phi = 0;
        float _alpha = 0.5;

**Comment by Tinyu-Zhao** [comment]
We have solved this problem, you can update the local library to try it
