### ISSUE TITLE
LED (Incl. matrix) not working wit Arduino ESP32 version 2.0.0

### ISSUE THREAD

**Issue by DietmarHoch** [m5stack/M5Atom#53]
The LEDs in the Examples are not working with the new ESP32 2.0.0

**Comment by felmue** [comment]
Hello @DietmarHoch 

this [pull-request](https://github.com/FastLED/FastLED/pull/1308) fixing FastLED resolved the issue for me.

Thanks
Felix

**Comment by DietmarHoch** [comment]
this works for me, waiting for integration in the master branch
