### ISSUE TITLE
Change naming of Button from Btn to BtnA

### ISSUE THREAD

**Issue by pierreverbakel** [m5stack/M5Atom#6]
In order for reuse of sketch-code, I would suggest to keep the naming of the first Button in M5-Atom the same as in M5Stack and M5Stick

Button Btn = Button(39, true, 10);
-> Change to:
Button BtnA = Button(39, true, 10);

**Comment by Hades2001** [comment]
Thanks for the suggestion, I have added a macro to the program to be compatible with BanA and the current program and update it in the next version
