### ISSUE TITLE
Missing datasheet for ATOM QR-CODE Kit

### ISSUE THREAD

**Issue by geiseri** [m5stack/M5Atom#61]
It seems the programming instructions are incomplete for the reader.  I tried the examples and there was not clear what was coming back.  Is there a more complete document for the protocol?  There is a document with QR codes, but not how to send those to the reader via the uart.  Thanks!

**Comment by Tinyu-Zhao** [comment]
This [document](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/atombase/AtomicQR/ATOM_QRCODE_CMD_EN.pdf) may be helpful to you
