### ISSUE TITLE
ATOM QR-CODE Kit, wrapper in C#

### ISSUE THREAD

**Issue by JORGEGO** [m5stack/M5Atom#67]
Dear M5Stack team,
I am developing a smart device using your technology M5Stack and nanoFramework, one of the components I need to integrate is the ATOM QR-Code Kit. The problem is how to do it, you suggest downloading your software with your utility easyloader (https://docs.m5stack.com/en/atom/atomic_qr) but that is not a valid solution, because it overwrites the nanoFramework image. So I need your software as a NuGet component where I could call from my program write in c#. Could you help me?
Thanks a lot

**Comment by Tinyu-Zhao** [comment]
Thank you for reaching out and for your interest in using our product.

Unfortunately, we do not have any plans to create a NuGet component or provide support for integration with nanoFramework at this time. We apologize for any inconvenience this may cause.

Please let us know if there is anything else we can assist you with.
