### ISSUE TITLE
What can i do with it?

### ISSUE THREAD

**Issue by Kriftoft** [m5stack/M5Atom#70]
Znaleziono wiele bibliotek w "WiFi.h"
PlayMP3FromSD:22:10: fatal error: AudioFileSourceSD.h: No such file or directory
Wykorzystane: C:\Users\sikor\OneDrive\Dokumenty\ArduinoData\packages\m5stack\hardware\esp32\2.0.3\libraries\WiFi
 #include "AudioFileSourceSD.h"
Niewykorzystane: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\libraries\WiFi
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
AudioFileSourceSD.h: No such file or directory

**Comment by Tinyu-Zhao** [comment]
Obviously you are missing the file AudioFileSourceSD.h, you should fill in the relevant information according to the question template, so that I can help you more
