### ISSUE TITLE
ESP32_PICO Image, possible damage

### ISSUE THREAD

**Issue by JORGEGO** [m5stack/M5Atom#72]
### Describe the bug

After installed: Extracting ESP32_PICO-1.8.0.629.zip...OK
Visual Studio does not recognize my device.
I used Putty connect to the COMx and PSRAM error produced

### To reproduce

Could confirm
nanoff --target ESP32_PICO --update --serialport COM6 --fwversion 1.8.0.594
works
after that do not recognize and fails device explorer

### Expected behavior

Install last firmware and recognize by VS Device Explorer

### Screenshots

![issue](https://user-images.githubusercontent.com/3842104/194310982-6bf2effb-6039-4d68-a00a-ccc96861fa2b.png)

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Atom/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Questo non sembra essere un problema legato alla libreria M5Atom.
