### ISSUE TITLE
Current release does not include the following breaking bug fix : extended character “ is not valid in an identifier #83

### ISSUE THREAD

**Issue by thomasfredericks** [m5stack/M5Atom#84]
### Describe the bug

The current release, available through the Arduino Library Manager, does not include the following breaking bug fix #83 

The latest version=0.1.2 of the Library cannot compile.

### To reproduce

Latest release version 0.1.2

### Expected behavior

#83 fixes this

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Atom/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
ok ,I will release this version

**Comment by thomasfredericks** [comment]
Thank you!
